### PR TITLE
finish parts of contact section

### LINKED ISSUE #18: Contact us section
As a user, I want to be able to contact the site administrator as I browse the site. When I see the ‘Contact Us’ button and information on the site, I want to be able to click on it and be navigated to a page so that I can easily find and use the contact form.

Display the ‘Contact Us’ button:
On every page of the website, users will see a visible ‘Contact Us’ button.
The text displayed on the button should read ‘Contact Us’.

Clickability of the button:
Users can click on the ‘Contact Us’ button.
Upon clicking the button, the user should be navigated to the Contact Us page.

Content of the Contact Us area:
The title is ‘X’.
The description is ‘xxxxxxxxxx’.

### PR DESCRIPTION
**Pull request by codeWorld666**
image

The interface I finished:
image

### CODE REVIEW

**Comment by RuntaoZhuge** [comment]
[acf-export-2024-06-06.json](https://github.com/user-attachments/files/15613371/acf-export-2024-06-06.json)
This is the acf changes I made

**Comment by codeWorld666** [comment]
acf-export-2024-06-06.json

**Comment by codeWorld666** [comment]
[acf-export-2024-06-06.json](https://github.com/user-attachments/files/15613397/acf-export-2024-06-06.json)

**Comment by codeWorld666** [comment]
image

**Comment by RuntaoZhuge** [comment]
Make sure you pr when you have finished everything

**Pull request closed without merging**
