### PR TITLE
2 user can navigate to different pages using the navigation bar

### LINKED ISSUE #2: nav bar section
As a website user,I want to use the navigation bar to quickly access different parts of the website, so that I can conveniently browse the content I'm interested in.

Image

### PR DESCRIPTION
**Pull request by Tracy-maker**
Screenshot 2024-06-10 at 10 32 30 PM
Screenshot 2024-06-10 at 10 32 22 PM

### CODE REVIEW

**Comment by Tracy-maker** [comment]
create pull request

**Comment by Tracy-maker** [comment]
click wrong button

**Comment by RuntaoZhuge** [comment]
Can you resolve the conflicts?

**Comment by RuntaoZhuge** [comment]
I fixed the conflicts but here is what it looks like on mine. Please pull the latest code and have a look
image

**Review by RuntaoZhuge — CHANGES_REQUESTED** [review]
That's mb. It's working fine

**Pull request merged**
